/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.tdlsoftware.libabf;

public class AbfDecoder {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AbfDecoder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AbfDecoder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libabfJNI.delete_AbfDecoder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AbfDecoder(String Filename) {
    this(libabfJNI.new_AbfDecoder__SWIG_0(Filename), true);
  }

  public AbfDecoder() {
    this(libabfJNI.new_AbfDecoder__SWIG_1(), true);
  }

  public void Initialize(String Filename) {
    libabfJNI.AbfDecoder_Initialize(swigCPtr, this, Filename);
  }

  public void Reset() {
    libabfJNI.AbfDecoder_Reset(swigCPtr, this);
  }

  public boolean IsValid() {
    return libabfJNI.AbfDecoder_IsValid(swigCPtr, this);
  }

  public boolean IsOpen() {
    return libabfJNI.AbfDecoder_IsOpen(swigCPtr, this);
  }

  public String GetTitle() {
    return libabfJNI.AbfDecoder_GetTitle(swigCPtr, this);
  }

  public String GetAuthor() {
    return libabfJNI.AbfDecoder_GetAuthor(swigCPtr, this);
  }

  public String GetTime() {
    return libabfJNI.AbfDecoder_GetTime(swigCPtr, this);
  }

  public int GetNumSections() {
    return libabfJNI.AbfDecoder_GetNumSections(swigCPtr, this);
  }

  public int GetHeaderSize() {
    return libabfJNI.AbfDecoder_GetHeaderSize(swigCPtr, this);
  }

  public int GetMajor() {
    return libabfJNI.AbfDecoder_GetMajor(swigCPtr, this);
  }

  public int GetMinor() {
    return libabfJNI.AbfDecoder_GetMinor(swigCPtr, this);
  }

  public boolean feof() {
    return libabfJNI.AbfDecoder_feof(swigCPtr, this);
  }

  public int ftell() {
    return libabfJNI.AbfDecoder_ftell(swigCPtr, this);
  }

  public void fclose() {
    libabfJNI.AbfDecoder_fclose(swigCPtr, this);
  }

  public int Seek(int offset, int whence) {
    return libabfJNI.AbfDecoder_Seek(swigCPtr, this, offset, whence);
  }

  public SWIGTYPE_p_int GetSections() {
    long cPtr = libabfJNI.AbfDecoder_GetSections(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void Decode(SWIGTYPE_p_short Output) {
    libabfJNI.AbfDecoder_Decode(swigCPtr, this, SWIGTYPE_p_short.getCPtr(Output));
  }

  public boolean GoToPosition(int Minutes) {
    return libabfJNI.AbfDecoder_GoToPosition(swigCPtr, this, Minutes);
  }

}
