/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.tdlsoftware.libabf;

public class libabfJNI {
  public final static native long new_AbfDecoder__SWIG_0(String jarg1);
  public final static native long new_AbfDecoder__SWIG_1();
  public final static native void delete_AbfDecoder(long jarg1);
  public final static native void AbfDecoder_Initialize(long jarg1, AbfDecoder jarg1_, String jarg2);
  public final static native void AbfDecoder_Reset(long jarg1, AbfDecoder jarg1_);
  public final static native boolean AbfDecoder_IsValid(long jarg1, AbfDecoder jarg1_);
  public final static native boolean AbfDecoder_IsOpen(long jarg1, AbfDecoder jarg1_);
  public final static native String AbfDecoder_GetTitle(long jarg1, AbfDecoder jarg1_);
  public final static native String AbfDecoder_GetAuthor(long jarg1, AbfDecoder jarg1_);
  public final static native String AbfDecoder_GetTime(long jarg1, AbfDecoder jarg1_);
  public final static native int AbfDecoder_GetNumSections(long jarg1, AbfDecoder jarg1_);
  public final static native int AbfDecoder_GetHeaderSize(long jarg1, AbfDecoder jarg1_);
  public final static native int AbfDecoder_GetMajor(long jarg1, AbfDecoder jarg1_);
  public final static native int AbfDecoder_GetMinor(long jarg1, AbfDecoder jarg1_);
  public final static native boolean AbfDecoder_feof(long jarg1, AbfDecoder jarg1_);
  public final static native int AbfDecoder_ftell(long jarg1, AbfDecoder jarg1_);
  public final static native void AbfDecoder_fclose(long jarg1, AbfDecoder jarg1_);
  public final static native int AbfDecoder_Seek(long jarg1, AbfDecoder jarg1_, int jarg2, int jarg3);
  public final static native long AbfDecoder_GetSections(long jarg1, AbfDecoder jarg1_);
  public final static native void AbfDecoder_Decode(long jarg1, AbfDecoder jarg1_, long jarg2);
  public final static native boolean AbfDecoder_GoToPosition(long jarg1, AbfDecoder jarg1_, int jarg2);
  public final static native long new_AbfEncoder__SWIG_0(String jarg1);
  public final static native long new_AbfEncoder__SWIG_1();
  public final static native void AbfEncoder_Initialize(long jarg1, AbfEncoder jarg1_, String jarg2);
  public final static native void delete_AbfEncoder(long jarg1);
  public final static native void AbfEncoder_SetTitle(long jarg1, AbfEncoder jarg1_, String jarg2);
  public final static native void AbfEncoder_SetAuthor(long jarg1, AbfEncoder jarg1_, String jarg2);
  public final static native void AbfEncoder_SetTime(long jarg1, AbfEncoder jarg1_, String jarg2);
  public final static native void AbfEncoder_SetNumSections(long jarg1, AbfEncoder jarg1_, int jarg2);
  public final static native void AbfEncoder_WriteHeader(long jarg1, AbfEncoder jarg1_);
  public final static native void AbfEncoder_WriteSection(long jarg1, AbfEncoder jarg1_);
  public final static native void AbfEncoder_Encode(long jarg1, AbfEncoder jarg1_, long jarg2);
}
