/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class AbfEncoder : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AbfEncoder(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(AbfEncoder obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~AbfEncoder() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libabfPINVOKE.delete_AbfEncoder(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public AbfEncoder(string Filename) : this(libabfPINVOKE.new_AbfEncoder__SWIG_0(Filename), true) {
  }

  public AbfEncoder() : this(libabfPINVOKE.new_AbfEncoder__SWIG_1(), true) {
  }

  public void Initialize(string arg0) {
    libabfPINVOKE.AbfEncoder_Initialize(swigCPtr, arg0);
  }

  public void SetTitle(string Title) {
    libabfPINVOKE.AbfEncoder_SetTitle(swigCPtr, Title);
  }

  public void SetAuthor(string Author) {
    libabfPINVOKE.AbfEncoder_SetAuthor(swigCPtr, Author);
  }

  public void SetTime(string Time) {
    libabfPINVOKE.AbfEncoder_SetTime(swigCPtr, Time);
  }

  public void SetNumSections(ushort NumSections) {
    libabfPINVOKE.AbfEncoder_SetNumSections(swigCPtr, NumSections);
  }

  public void WriteHeader() {
    libabfPINVOKE.AbfEncoder_WriteHeader(swigCPtr);
  }

  public void WriteSection() {
    libabfPINVOKE.AbfEncoder_WriteSection(swigCPtr);
  }

  public void Encode(SWIGTYPE_p_short Input) {
    libabfPINVOKE.AbfEncoder_Encode(swigCPtr, SWIGTYPE_p_short.getCPtr(Input));
  }

}
