/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

class libabfPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [DllImport("libabf", EntryPoint="SWIGRegisterExceptionCallbacks_libabf")]
    public static extern void SWIGRegisterExceptionCallbacks_libabf(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [DllImport("libabf", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_libabf")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_libabf(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_libabf(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_libabf(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [ThreadStatic]
    private static Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(Exception e) {
      if (pendingException != null)
        throw new ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(libabfPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static Exception Retrieve() {
      Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(libabfPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [DllImport("libabf", EntryPoint="SWIGRegisterStringCallback_libabf")]
    public static extern void SWIGRegisterStringCallback_libabf(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_libabf(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static libabfPINVOKE() {
  }


  [DllImport("libabf", EntryPoint="CSharp_new_AbfDecoder__SWIG_0")]
  public static extern IntPtr new_AbfDecoder__SWIG_0(string jarg1);

  [DllImport("libabf", EntryPoint="CSharp_new_AbfDecoder__SWIG_1")]
  public static extern IntPtr new_AbfDecoder__SWIG_1();

  [DllImport("libabf", EntryPoint="CSharp_delete_AbfDecoder")]
  public static extern void delete_AbfDecoder(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_Initialize")]
  public static extern void AbfDecoder_Initialize(HandleRef jarg1, string jarg2);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_Reset")]
  public static extern void AbfDecoder_Reset(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_IsValid")]
  public static extern bool AbfDecoder_IsValid(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_IsOpen")]
  public static extern bool AbfDecoder_IsOpen(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_GetTitle")]
  public static extern string AbfDecoder_GetTitle(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_GetAuthor")]
  public static extern string AbfDecoder_GetAuthor(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_GetTime")]
  public static extern string AbfDecoder_GetTime(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_GetNumSections")]
  public static extern ushort AbfDecoder_GetNumSections(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_GetHeaderSize")]
  public static extern ushort AbfDecoder_GetHeaderSize(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_GetMajor")]
  public static extern ushort AbfDecoder_GetMajor(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_GetMinor")]
  public static extern ushort AbfDecoder_GetMinor(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_feof")]
  public static extern bool AbfDecoder_feof(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_ftell")]
  public static extern int AbfDecoder_ftell(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_fclose")]
  public static extern void AbfDecoder_fclose(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_Seek")]
  public static extern int AbfDecoder_Seek(HandleRef jarg1, int jarg2, int jarg3);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_GetSections")]
  public static extern IntPtr AbfDecoder_GetSections(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_Decode")]
  public static extern void AbfDecoder_Decode(HandleRef jarg1, HandleRef jarg2);

  [DllImport("libabf", EntryPoint="CSharp_AbfDecoder_GoToPosition")]
  public static extern bool AbfDecoder_GoToPosition(HandleRef jarg1, int jarg2);

  [DllImport("libabf", EntryPoint="CSharp_new_AbfEncoder__SWIG_0")]
  public static extern IntPtr new_AbfEncoder__SWIG_0(string jarg1);

  [DllImport("libabf", EntryPoint="CSharp_new_AbfEncoder__SWIG_1")]
  public static extern IntPtr new_AbfEncoder__SWIG_1();

  [DllImport("libabf", EntryPoint="CSharp_AbfEncoder_Initialize")]
  public static extern void AbfEncoder_Initialize(HandleRef jarg1, string jarg2);

  [DllImport("libabf", EntryPoint="CSharp_delete_AbfEncoder")]
  public static extern void delete_AbfEncoder(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfEncoder_SetTitle")]
  public static extern void AbfEncoder_SetTitle(HandleRef jarg1, string jarg2);

  [DllImport("libabf", EntryPoint="CSharp_AbfEncoder_SetAuthor")]
  public static extern void AbfEncoder_SetAuthor(HandleRef jarg1, string jarg2);

  [DllImport("libabf", EntryPoint="CSharp_AbfEncoder_SetTime")]
  public static extern void AbfEncoder_SetTime(HandleRef jarg1, string jarg2);

  [DllImport("libabf", EntryPoint="CSharp_AbfEncoder_SetNumSections")]
  public static extern void AbfEncoder_SetNumSections(HandleRef jarg1, ushort jarg2);

  [DllImport("libabf", EntryPoint="CSharp_AbfEncoder_WriteHeader")]
  public static extern void AbfEncoder_WriteHeader(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfEncoder_WriteSection")]
  public static extern void AbfEncoder_WriteSection(HandleRef jarg1);

  [DllImport("libabf", EntryPoint="CSharp_AbfEncoder_Encode")]
  public static extern void AbfEncoder_Encode(HandleRef jarg1, HandleRef jarg2);

  [DllImport("libabf", EntryPoint="CSharp_DecodeToRawAudio")]
  public static extern string DecodeToRawAudio(string jarg1);

  [DllImport("libabf", EntryPoint="CSharp_EncodeABF")]
  public static extern bool EncodeABF(HandleRef jarg1, string jarg2);
}
