/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class libabf {
  public static string DecodeToRawAudio(string Filename) {
    string ret = libabfPINVOKE.DecodeToRawAudio(Filename);
    return ret;
  }

  public static bool EncodeABF(AbfEncoder AE, string TempFile) {
    bool ret = libabfPINVOKE.EncodeABF(AbfEncoder.getCPtr(AE), TempFile);
    if (libabfPINVOKE.SWIGPendingException.Pending) throw libabfPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
