.\" $Id$
.\" A first draft manual page for abfconverter
.\" This is only a draft page - as such, we do not really know whether it will display properly.
.\" I hope it will prove useful.
.Dd February 24, 2019
.Dt ABFCONVERTER 1
.Os
.Sh NAME
.Nm abfconverter
.Nd A program to convert DAISY books to ABF Audio Books.
.Sh Description
.Nm
takes a Daisy 2.02 book and converts it to an ABF book to be played by abfplayer(1).
.Pp
.Nm
can encode at three different quality levels: Normal sample rate, higher quality or extreme quality.
.pp
To specify the quality, parse an optional -h or -x option after the ABF output file name.

.Sh AUTHORS
.An Peter Laursen

.Sh SEE ALSO
.Xr abfplayer 1

