.\" $Id$
.\" A first draft manual page for abfplayer
.\" This is only a draft page - as such, we do not really know whether it will display properly.
.\" I hope it will prove useful.
.Dd February 24, 2019
.Dt ABFPLAYER 1
.Os
.Sh NAME
.Nm abfplayer
.Nd A program to play ABF audio books.
.Sh Description
.Nm
is a program that allows you to play ABF audio books on Unix and Windows-based systems.
.Pp
On Windows, however, the Winamp plugin may be better suited to the people preferring a mouse.
.Sh Overview
.Nm
plays ABF audio books specified on the command line. Standard globbing can be used to ease locating files.

.Sh AUTHORS
.An Peter Laursen
.Sh SEE ALSO
.Xr abfconverter 1
