/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_LIBABF_H
#define PHP_LIBABF_H

extern zend_module_entry libabf_module_entry;
#define phpext_libabf_ptr &libabf_module_entry

#ifdef PHP_WIN32
# define PHP_LIBABF_API __declspec(dllexport)
#else
# define PHP_LIBABF_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(libabf);
PHP_MSHUTDOWN_FUNCTION(libabf);
PHP_RINIT_FUNCTION(libabf);
PHP_RSHUTDOWN_FUNCTION(libabf);
PHP_MINFO_FUNCTION(libabf);

ZEND_NAMED_FUNCTION(_wrap_new_AbfDecoder);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_Initialize);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_Reset);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_IsValid);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_IsOpen);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_GetTitle);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_GetAuthor);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_GetTime);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_GetNumSections);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_GetHeaderSize);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_GetMajor);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_GetMinor);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_feof);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_ftell);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_fclose);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_Seek);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_GetSections);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_Decode);
ZEND_NAMED_FUNCTION(_wrap_AbfDecoder_GoToPosition);
ZEND_NAMED_FUNCTION(_wrap_new_AbfEncoder);
ZEND_NAMED_FUNCTION(_wrap_AbfEncoder_Initialize);
ZEND_NAMED_FUNCTION(_wrap_AbfEncoder_SetTitle);
ZEND_NAMED_FUNCTION(_wrap_AbfEncoder_SetAuthor);
ZEND_NAMED_FUNCTION(_wrap_AbfEncoder_SetTime);
ZEND_NAMED_FUNCTION(_wrap_AbfEncoder_SetNumSections);
ZEND_NAMED_FUNCTION(_wrap_AbfEncoder_WriteHeader);
ZEND_NAMED_FUNCTION(_wrap_AbfEncoder_WriteSection);
ZEND_NAMED_FUNCTION(_wrap_AbfEncoder_Encode);
ZEND_NAMED_FUNCTION(_wrap_DecodeToRawAudio);
ZEND_NAMED_FUNCTION(_wrap_EncodeABF);
#endif /* PHP_LIBABF_H */
